// <auto-generated>
// Rewired Constants
// This list was generated on 15/09/2019 23:13:52
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        // Gameplay
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Buttons used in game", friendlyName = "Used to move up or down in game")]
        public const int MoveVertical = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Buttons used in game", friendlyName = "Used to move left or right in game")]
        public const int MoveHorizontal = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Buttons used in game", friendlyName = "Used to swing the racket")]
        public const int Swing = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Buttons used in game", friendlyName = "Used to charge an attack")]
        public const int Charge = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Buttons used in game", friendlyName = "Used to Dash")]
        public const int Dash = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Buttons used in game", friendlyName = "Pauses the game")]
        public const int Pause = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Buttons used in game", friendlyName = "BackToMenu")]
        public const int BackToMenu = 14;
        // Menu
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Buttons used in the menu", friendlyName = "Used to move up")]
        public const int MenuUp = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Buttons used in the menu", friendlyName = "Used to move down")]
        public const int MenuDown = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Buttons used in the menu", friendlyName = "Used to move right in menus")]
        public const int MenuRight = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Buttons used in the menu", friendlyName = "Used to move left in menus")]
        public const int MenuLeft = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Buttons used in the menu", friendlyName = "Selects a menu item")]
        public const int Select = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Buttons used in the menu", friendlyName = "Moves back in the menu cancels a selection")]
        public const int Back = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Buttons used in the menu", friendlyName = "Start")]
        public const int Start = 13;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Buttons used in the menu", friendlyName = "MenuHorizontal")]
        public const int MenuHorizontal = 15;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Buttons used in the menu", friendlyName = "MenuVertical")]
        public const int MenuVertical = 16;
    }
    public static partial class Category {
        public const int Default = 0;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
            public const int TypeA = 1;
            public const int TypeB = 3;
            public const int TypeC = 2;
            public const int Menu = 4;
            public const int Custom = 5;
        }
        public static partial class Keyboard {
            public const int Default = 0;
            public const int TypeA = 1;
            public const int Custom = 2;
            public const int Menu = 3;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player1")]
        public const int Player1 = 0;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player2")]
        public const int Player2 = 1;
    }
}
